### ISSUE TITLE
double outlineS when language=C/C++

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-anycode#1]
![image](https://user-images.githubusercontent.com/1876302/132819716-905a38da-47fb-4033-b1a4-45232f82d6a8.png)
BTW: the file ext is "`*.pln`"

**Comment by jrieken** [comment]
That's kinda designed - when having multiple extensions installed that provide outline than this happening. This can only be resolved through setup/configuration, like not install multiple extensions or use extension config. Anycode has a big toggle per language for this, e.g `anycode.language.cpp.enabled`

**Comment by jrieken** [comment]
With latest anycode there is now `anycode.language.features` which can be configured per language, like so

```json
 "[typescript]": {
        "anycode.language.features": {
            "completions": true,
            "definitions": true,
            "references": true,
            "highlights": false,
            "outline": false,
            "workspaceSymbols": true,
            "diagnostics": false
        }
    },
```

**Comment by heartacker** [comment]
thanks @jrieken
