### ISSUE TITLE
Troubleshooting Highlighting on New Language Extension

### ISSUE THREAD

**Issue by aheber** [microsoft/vscode-anycode#100]
I'm working on building an extension to support Salesforce's Apex language in `anycode`. I already have a tree-sitter grammar definition @ https://github.com/aheber/tree-sitter-sfapex

I have the new extension generally built and functional for some features such as finding references. This is wonderfully exciting to see something working.
<img width="825" alt="image" src="https://github.com/user-attachments/assets/b147922c-2052-47bb-8e4e-2fdc8f3ccfa9">

I think I have rough versions of the various query files created and functional and they are working in some cases. I'm not able to figure out how to get the highlighting working inside of VS Code. I have the `fixtures/highlights.cls` file created and passing tests. I don't know why the highlighting isn't applied inside of the VS Code editor experience. (desktop/node)

If I use `Developer: Inspect Editor Tokens and Scopes` in VS Code it tells me "No grammar or semantic tokens available." where I would expect `anycode` to be providing something, if I'm understanding it's capabilities correctly.

If there is something simple please point me in the right direction. If you need to see the code/project to troubleshoot I'm happy to make it available.

**Comment by jrieken** [comment]
>  I'm not able to figure out how to get the highlighting working inside of VS Code. I have the fixtures/highlights.cls file created and passing tests. I don't know why the highlighting isn't applied inside of the VS Code editor experience. (desktop/node)

This currently isn't possible - neither with anycode nor with vscode. However, there is an effort to support treesitter based highlights directly within vscode. However, the latter is currently being worked on and we might be able to open this up for extensions in the near future

**Comment by aheber** [comment]
Thank you for the response. Is there a specific issue on the VSCode side that tracks this effort?
