### ISSUE TITLE
Custom language support

### ISSUE THREAD

**Issue by EightM** [microsoft/vscode-anycode#11]
Is anycode open for adding support for languages that does not include in VS code?

For example if i have some language Foo, tree-sitter-foo library and Foo syntax highlight extension, what the best way to add this language to anycode? Thanks.

**Comment by jrieken** [comment]
> For example if i have some language Foo, tree-sitter-foo library and Foo syntax highlight extension,

Yeah, in principle this is open for contributions but YSK that anycode isn't about syntax highlighting. I am therefore a little confused by your statement about syntax highlighting above. Anycode is about low fidelity language services features, like outline or go to definition etc

**Comment by EightM** [comment]
>I am therefore a little confused by your statement about syntax highlighting

Oh, so i can just use two separate extension, right? In Anycode it will be tree-sitter-foo and activation event "onLanguage: Foo" and some other separate web extension will contribute new language Foo to VS code and provide its syntax highlighting

**Comment by jrieken** [comment]
Yes - that should work. What language is that?

**Comment by EightM** [comment]
>What language is that?
It's just a simple script language that is quite popular in my country. 
Thanks for help!
