### ISSUE TITLE
Question: Simplicity of adding a language

### ISSUE THREAD

**Issue by borgdylan** [microsoft/vscode-anycode#16]
What are the necessary steps to add a new language (given that a grammer already exists for code) to anycode. I do not require to add it to the repo, but just have it work on my machine.

**Comment by jrieken** [comment]
There is no real contribution story for grammars and today languages are hardcoded into the extension. A couple of pieces are involved

* add the grammar via npm, like [here](https://github.com/microsoft/vscode-anycode/blob/e23605c0fa438a07555a200a993c06d1ad8ee855/server/package.json#L29)
* enroll the grammar and some metadata like [here](https://github.com/microsoft/vscode-anycode/blob/8290551b8194a05b44582fd295a668c2ce736272/client/src/supportedLanguages.ts#L52)
* write queries that extract the wanted information from a syntax tree, e.g [outline for rust](https://github.com/microsoft/vscode-anycode/blob/1cc17ca5945e0ddf465e0ec010888fba049fd509/server/src/queries/rust/outline.scm) etc. This isn't documented but the most laborious part. Also query capture names have some semantics which aren't documented/finalized yet
* add tests

Ideally, this can happen from the outside. The anycode extension could define a contribution point to which other extensions contribute static data (wasm, metainfo, queries) which is then processed. That would make the contribution story the simplest and easier to maintain

**Comment by borgdylan** [comment]
I did not know that an extra custom parser had to be written (thought tree-sitter was a generic parser fed with textmate grammars). I do not have the requirement to run in the browser and already have a parser written in the language itself (compiles to standard .NET libraries). Would it be more practical for me to attempt writing a Language Server instead? If so, are there any "shell" language servers for .NET where I could implement a set of interfaces only?

**Comment by jrieken** [comment]
Yes - if you already have a custom parser and language service you should write a language server instead. You can find various SDK that help LSP here https://microsoft.github.io/language-server-protocol/implementors/sdks/

**Comment by borgdylan** [comment]
Thank you. I found https://github.com/OmniSharp/csharp-language-server-protocol . I have a parser but not a language service. The compiler is split into libraries with the lexer and parser having public facades for direct consumption. Is Omnisharp written using https://github.com/OmniSharp/csharp-language-server-protocol ? If yes, it would be the best ever example.

**Comment by jrieken** [comment]
>  Is Omnisharp written using https://github.com/OmniSharp/csharp-language-server-protocol ? If yes, it would be the best ever example.

My involvement in OmniSharp is too long ago to know this. Tho, given it is in their org I'd say it's likely used

**Comment by jrieken** [comment]
Closing this issue which was more of a question. However, we do plan to make contributing tree-sitter based goodness simpler: https://github.com/microsoft/vscode-anycode/issues/24
