### ISSUE TITLE
Request file/read failed with message: No file system provider found for resource

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-anycode#19]
- Extension version: v0.35.2021121509
- VSCode Version: 1.64-insider (insiders.vscode.dev)
- OS: Windows 11

Steps to Reproduce:

1. Go to https://insiders.vscode.dev/github/python/cpython/pull/29581
2. Open a bunch of modified files in the diff editor very quickly
3. 🐛 see this error message a lot in dev tools: 
![image](https://user-images.githubusercontent.com/30305945/146226395-6404b49c-cf0f-4e99-81a5-3696bc9fe78d.png)

**Comment by jrieken** [comment]
Thanks for investigating @alexr00
