### ISSUE TITLE
Make anycode a web and desktop extension

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-anycode#23]
On desktop, AnyCode runs in webworker ext host and RemoteHub runs in Node ext host. This means AnyCode cannot acquire RemoteHub's API and this will always use the 500 file mode. RemoteHub runs in Node so that it can be used by GHPRI. These extensions should all run in the same ext host. (cc @alexr00 , @joyceerhl )

**Comment by jrieken** [comment]
related to https://github.com/microsoft/vscode/issues/133734
