### ISSUE TITLE
Reference search shows matches in the same file under different paths

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-anycode#25]
- open https://github.dev/python/cpython/pull/29581
- open `Include/internal/pycore_ast.h`
- do a reference search for the enum `FunctionDef_kind`

-> the same match is reported twice in different files, but there is only a single `pycore_ash.t` in this repository
![image](https://user-images.githubusercontent.com/172399/157448782-c4ea5a69-7f9c-4df9-9c96-3bd0fc83d877.png)

**Comment by jrieken** [comment]
Looks like there is two variants of this file: one is the actual file (`vscode-vfs`-scheme) and another one seems to be from the `review`-scheme. I assume the later is from GHPR extension and should be filtered

<img width="1127" alt="Screenshot 2022-03-09 at 17 01 37" src="https://user-images.githubusercontent.com/1794099/157480127-196fbfdf-a257-4dde-ac66-7d714ce7d210.png">

**Comment by jrieken** [comment]
Instead of having the static filter-list we should probably have an allow list which is all schemas file-search found - plus some special scheme, like notebooks
