### ISSUE TITLE
Go: go to definition doesn't work for typealiases

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode-anycode#3]
Testing [#2389](https://github.com/microsoft/vscode-internalbacklog/issues/2389)

`statusHandler` is defined above as an `int` but go to definition doesn't go to it.

![image](https://user-images.githubusercontent.com/12758612/135146464-49940e5a-7507-43b0-8e87-2763f31eefa4.png)

**Comment by jrieken** [comment]
@tanhakabir please share the repo/code that you have been using

**Comment by tanhakabir** [comment]
This is the repo: https://github.dev/golang/example

**Comment by jrieken** [comment]
Doesn't reproduce with anycode@0.0.36 and insiders
