### ISSUE TITLE
Go: inconsistent outline for variables defined in for loops

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode-anycode#4]
Testing [#2389](https://github.com/microsoft/vscode-internalbacklog/issues/2389)

Shows `in` in the outline but not `want`:
![image](https://user-images.githubusercontent.com/12758612/135146954-156cf2a5-6a5e-4f44-9070-5711748b7e0b.png)

Doesn't show any variables in the outline:
![image](https://user-images.githubusercontent.com/12758612/135147084-34ba2ddd-69b7-4ac3-af7d-90d4d68927e1.png)

**Comment by jrieken** [comment]
It's not the idea to show locals in outline. However, in the first sample the loop defines a struct-type (nameless) and outline only shows one of its properties (`in` ignores `want`)

**Comment by jrieken** [comment]
@tanhakabir I can actually not reproduce. Can you give this another try with anycode@0.0.35 or later? Also, please the repo/files you tried this with

<img width="511" alt="Screen Shot 2021-09-29 at 14 45 48" src="https://user-images.githubusercontent.com/1794099/135270984-025237ac-f865-4965-904b-99b6f1d92f05.png">

**Comment by tanhakabir** [comment]
This is the repo I was working with: https://github.dev/golang/example

Testing with 0.0.36 now
