### ISSUE TITLE
Only work for some languages

### ISSUE THREAD

**Issue by dufferzafar** [microsoft/vscode-anycode#8]
Currently, If anycode is installed, it takes precedence over other extensions like Python etc.

Is there a way to use anycode for C++/Rust/Go (languages that I don't use enough to justify a full blown extension) but keep using Python/Pylance for python files.

**Comment by jrieken** [comment]
Yes, there is the `anycode.language.features`-setting which can be configure per language, e.g this setting.json snippet is how you turn everything off for python

```json
"[python]": {
        "anycode.language.features": {
            "completions": false,
            "definitions": false,
            "references": false,
            "highlights": false,
            "outline": false,
            "workspaceSymbols": false,
            "diagnostics": false
        }
    },
```
