### ISSUE TITLE
Remove/adjust index size limit of 100 files

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-anycode#9]
By default we cap the file index at 100 files. This is done for performance reasons and to prevent GH.com load. Tho, when using anycode together with remotehub (which is the likely case) we have a tar-based file system. We should make sure that's always used for anycode and remove the file limit. We should also investigate in other fs perf tricks

**Comment by JacksonKearl** [comment]
Next release of remotehub will have an option to auto-download repos when the size is less than a given amount, that should resolve this.

**Comment by JacksonKearl** [comment]
Next release of RemoteHub will download tars by default. I think we should not download additional files when the user has explicitly opted out of indexing, either a) their network is very poor and hammering it with network requests would be ill-advised or b) the repo is very large and downloading some fixed 100 files is likely of little use.

**Comment by jrieken** [comment]
Closing, we are good on this
